 
 GET http://localhost:3000/api/user
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiZHVsIiwidXNlciI6eyJ1c2VybmFtZSI6ImFiZHVsIiwicGFzc3dvcmQiOiIkMmIkMTAkVU56djNCTUNCQkVOVXRkb3QwQk9pLllVVWo0Y2tJOENlUFE5Z3JyR0JBTlZ6OXJ1aWhyaDYiLCJuYW1lIjoiU2VuYWR1bmciLCJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW1GaVpIVnNJaXdpYm1GdFpTSTZJbTFoYW1sa0lpd2lhV0YwSWpveE5qa3hNak00T0RjMUxDSmxlSEFpT2pFMk9URXpNalV5TnpWOS5KR09fdkFPVHZxbW9nbWdXNVN2Zm84QTNVRjc5X0tXOHFwV1JZN2RIdE9vIn0sImlhdCI6MTY5MTI5Mjk4NywiZXhwIjoxNjkxMjkzMTQ3fQ.6hiqLKQSAtaTToUj_sGm3fHxubvR7sNcSXd5WjXq62w

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "username": "abdul",
  "password" : "123"
}

###
GET http://localhost:3000/api/user/token
###
GET http://localhost:3000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiZHVsIiwidXNlciI6eyJ1c2VybmFtZSI6ImFiZHVsIiwicGFzc3dvcmQiOiIkMmIkMTAkVU56djNCTUNCQkVOVXRkb3QwQk9pLllVVWo0Y2tJOENlUFE5Z3JyR0JBTlZ6OXJ1aWhyaDYiLCJuYW1lIjoibWFqaWQiLCJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW1GaVpIVnNJaXdpYm1GdFpTSTZJbTFoYW1sa0lpd2lhV0YwSWpveE5qa3hNak00T0RjMUxDSmxlSEFpT2pFMk9URXpNalV5TnpWOS5KR09fdkFPVHZxbW9nbWdXNVN2Zm84QTNVRjc5X0tXOHFwV1JZN2RIdE9vIn0sImlhdCI6MTY5MTI5MjY4MCwiZXhwIjoxNjkxMjkyODQwfQ.PlyXEpEK8Y2KE15ykmSsjEj0bQThrxaFZJwZYWt9Uk8

###
PATCH  http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiZHVsIiwidXNlciI6eyJ1c2VybmFtZSI6ImFiZHVsIiwicGFzc3dvcmQiOiIkMmIkMTAkVU56djNCTUNCQkVOVXRkb3QwQk9pLllVVWo0Y2tJOENlUFE5Z3JyR0JBTlZ6OXJ1aWhyaDYiLCJuYW1lIjoibWFqaWQiLCJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW1GaVpIVnNJaXdpYm1GdFpTSTZJbTFoYW1sa0lpd2lhV0YwSWpveE5qa3hNak00T0RjMUxDSmxlSEFpT2pFMk9URXpNalV5TnpWOS5KR09fdkFPVHZxbW9nbWdXNVN2Zm84QTNVRjc5X0tXOHFwV1JZN2RIdE9vIn0sImlhdCI6MTY5MTI5Mjg2NCwiZXhwIjoxNjkxMjkzMDI0fQ.U3i1S1zdsLyuCQBaxSChvdkI6RwUb-_O5On3nbByelI
Content-Type: application/json

{
  "name":"Senadung"
}